version: "3.4"
services:
  besu:
    image: suburbandad/besu:kintsugi-v3
    container_name: besu
    volumes:
      - ./execution_data:/execution_data
      - ../../../$TESTNET_NAME/custom_config_data:/custom_config_data
    command: >
      --data-path="/execution_data"
      --genesis-file="/custom_config_data/besu_genesis.json"
      --network-id=$NETWORK_ID
      --rpc-http-enabled=true
      --rpc-ws-enabled=true
      --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION
      --rpc-ws-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --p2p-enabled=true
      --Xmerge-support=true
      --miner-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-ws-host=0.0.0.0
      --p2p-host=$IP_ADDRESS
      --bootnodes=$ENODE
      --miner-coinbase="0xFE3B557E8Fb62b89F4916B721be55cEb828dBd73"
    network_mode: host
  teku_beacon:
    image: consensys/teku:develop
    container_name: teku_beacon
    volumes:
      - ./beacon_data:/consensus_data
      - ../../../$TESTNET_NAME/custom_config_data:/custom_config_data
    command: >
      --network "/custom_config_data/config.yaml"
      --initial-state "/custom_config_data/genesis.ssz"
      --data-path "/consensus_data" --data-storage-mode=PRUNE
      --validator-keys=/consensus_data/validator/keys:/consensus_data/validator/secrets
      --p2p-enabled=true --eth1-endpoints=http://127.0.0.1:8545
      --Xee-endpoint=http://127.0.0.1:8545
      --p2p-advertised-ip=$IP_ADDRESS --p2p-discovery-bootnodes=$ENR
      --rest-api-enabled=true --rest-api-docs-enabled=true
      --rest-api-interface=0.0.0.0 --rest-api-port=4000
      --rest-api-host-allowlist=* --Xdata-storage-non-canonical-blocks-enabled=true
      --Xnetwork-merge-total-terminal-difficulty=$TOTAL_TERMINAL_DIFFICULTY
      --Xvalidators-suggested-fee-recipient-address=0x2f14582947E292a2eCd20C430B46f2d27CFE213c
      --log-destination=CONSOLE
    network_mode: host
